name: mpg-horses
channels:
  - conda-forge
  - defaults
dependencies:
  # Core packages with versions
  - python=3.13
  - jupyter=1.1
  - numpy=2.2
  - pandas=2.2
  - matplotlib
  - seaborn
  - geopandas=1.0
  - gdal=3.10
  - rasterio=1.4
  - scikit-learn=1.6
  - tqdm
  - gspread
  - jupytext
  - pyarrow
  # ML packages
  - huggingface_hub
  - datasets
  - pytorch
  - torchvision
  - transformers
  # Let conda resolve other dependencies automatically