name: mpg-horses
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core packages with versions
  - python=3.11
  - jupyter=1.1
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib
  - seaborn
  - geopandas=1.0
  - gdal=3.10
  - rasterio=1.4
  - scikit-learn>=1.3
  - tqdm
  - gspread
  - jupytext
  - pyarrow
  # ML packages
  - huggingface_hub
  - datasets
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - transformers
  # Additional dependencies
  - libgfortran
  - openblas
  # Let conda resolve other dependencies automatically